/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab8p2_carlosmoncada;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author calol
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        activarcombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        crearpais = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        sp_numeromedallas = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sp_records = new javax.swing.JSpinner();
        cb_estilos = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        cb_distanciaevento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nombrenadador = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cb_nacionalidad = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        sp_edadnadador = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        cb_estilo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb_distancia = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        sp_tiempomasrapido = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        sp_nummedallas = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        txt_estatura = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listapaises = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        cb_nadadoresagregar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nombre");

        crearpais.setText("Crear paises");
        crearpais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearpaisMouseClicked(evt);
            }
        });

        jLabel13.setText("Numero de medallas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(sp_numeromedallas, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(crearpais)))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sp_numeromedallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(crearpais)
                .addGap(104, 104, 104))
        );

        jTabbedPane1.addTab("Crear paises", jPanel1);

        jLabel3.setText("Distancia");

        jLabel4.setText("Records");

        cb_estilos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Pecho", "Dorso", "Mariposa" }));

        jButton1.setText("Crear evento");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        cb_distanciaevento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "200", "400", "800" }));

        jLabel1.setText("Estilos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(sp_records)
                                .addComponent(cb_estilos, 0, 135, Short.MAX_VALUE)
                                .addComponent(cb_distanciaevento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(417, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(cb_distanciaevento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sp_records, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_estilos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(65, 65, 65))
        );

        jTabbedPane1.addTab("Crear eventos", jPanel2);

        jLabel5.setText("Nombre");

        jLabel6.setText("Nacionalidad");

        jLabel7.setText("Edad");

        jLabel8.setText("Estatura");

        cb_estilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIBRE", "PECHO", "DORSO y MARIPOSA" }));

        jLabel9.setText("Estilo de natacion");

        jLabel10.setText("Distancia");

        cb_distancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "200", "400", "800" }));

        jLabel11.setText("Tiempo mas rapido");

        jLabel12.setText("Numero de medallas");

        jButton2.setText("Crear nadador");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(nombrenadador)
                            .addComponent(cb_nacionalidad, 0, 140, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(sp_edadnadador, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txt_estatura))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(cb_estilo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(cb_distancia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sp_tiempomasrapido)
                            .addComponent(sp_nummedallas)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jButton2)))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrenadador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_estilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_edadnadador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_tiempomasrapido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_nummedallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_estatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Crear Nadador", jPanel3);

        jButton3.setText("Eliminar pais");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        listapaises.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(listapaises);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jButton3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton3)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar Paises", jPanel4);

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar Nadadores", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(cb_nadadoresagregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(572, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cb_nadadoresagregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar nadador a pais", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearpaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearpaisMouseClicked
        String nombre = txt_nombre.getText();
        int nummedallas = (int) sp_numeromedallas.getValue();
        paises.add(new Pais(nombre, nummedallas));
        Pais a = new Pais();
        a.agregaralarchivo(paises.get(paises.size() - 1));
        txt_nombre.setText("");
        sp_numeromedallas.setValue(0);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_nacionalidad.getModel();
        modelo.addElement(paises.get(paises.size() - 1));
        cb_nacionalidad.setModel(modelo);
        DefaultListModel modelolista = (DefaultListModel) listapaises.getModel();
        modelolista.addElement(paises.get(paises.size() - 1));
        listapaises.setModel(modelolista);
    }//GEN-LAST:event_crearpaisMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String distancia = cb_distanciaevento.getSelectedItem() + "";
        int records = (int) sp_records.getValue();
        String estilos = cb_estilos.getSelectedItem() + "";
        eventos.add(new Eventos(estilos, distancia, records));
        agregareventoalarchivo(eventos.get(eventos.size() - 1));
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String nombre = nombrenadador.getText();
        Pais nacionalidad = (Pais) cb_nacionalidad.getSelectedItem();
        int edad = (int) sp_edadnadador.getValue();
        double estatura = Double.parseDouble(txt_estatura.getText());
        String estilo = cb_estilo.getSelectedItem() + "";
        String distancia = cb_distancia.getSelectedItem() + "";
        int tiempomasrapido = (int) sp_tiempomasrapido.getValue();
        int nummedallas = (int) sp_nummedallas.getValue();

        // DefaultListModel modelonadadores=(DefaultListModel)listanadadores.getModel();
        //modelonadadores.addElement(nadadores.get(nadadores.size()-1));
        //listanadadores.setModel(modelonadadores);
        if (estilo.equalsIgnoreCase("libre") && contlibre < 2) {
            nadadores.add(new Nadador(nombre, nacionalidad, edad, estatura, estilo, distancia, tiempomasrapido, nummedallas));
            agregarnadadoralarchivo(nadadores.get(nadadores.size() - 1));
            movercontadores(nadadores);
        } else {
            JOptionPane.showMessageDialog(this, "No se pueden agregar mas de libre");
        }
        if (estilo.equalsIgnoreCase("pecho") && contpecho < 2) {
         nadadores.add(new Nadador(nombre, nacionalidad, edad, estatura, estilo, distancia, tiempomasrapido, nummedallas));
            agregarnadadoralarchivo(nadadores.get(nadadores.size() - 1));
            movercontadores(nadadores);
        }else{
            JOptionPane.showMessageDialog(this, "No se pueden agregar mas de pecho");
        }
        if (estilo.equalsIgnoreCase("dorso") && contdorso < 2) {
            nadadores.add(new Nadador(nombre, nacionalidad, edad, estatura, estilo, distancia, tiempomasrapido, nummedallas));
            agregarnadadoralarchivo(nadadores.get(nadadores.size() - 1));
            movercontadores(nadadores);
        }else{
            JOptionPane.showMessageDialog(this, "No se pueden agregar mas de dorso");
        }
        if (estilo.equalsIgnoreCase("mariposa")&&contmariposa<2) {
             nadadores.add(new Nadador(nombre, nacionalidad, edad, estatura, estilo, distancia, tiempomasrapido, nummedallas));
            agregarnadadoralarchivo(nadadores.get(nadadores.size() - 1));
            movercontadores(nadadores);
        }else{
            JOptionPane.showMessageDialog(this, "No se pueden agregar mas de mariposa");
        
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if (listapaises.getSelectedIndex() >= 0) {
            DefaultListModel modelojlist = (DefaultListModel) listapaises.getModel();
            Pais p = (Pais) modelojlist.getElementAt(listapaises.getSelectedIndex());
            modelojlist.removeElementAt(listapaises.getSelectedIndex());
            DefaultComboBoxModel modelocombo = (DefaultComboBoxModel) cb_nacionalidad.getModel();
            modelocombo.removeElement(p);
            cb_nacionalidad.setModel(modelocombo);
            listapaises.setModel(modelojlist);

        }
    }//GEN-LAST:event_jButton3MouseClicked
    public void activarcombobox() {
        Pais x = new Pais();
        ArrayList<Pais> agregarpaises = x.leerarchivo();
        DefaultComboBoxModel modelopaises = (DefaultComboBoxModel) cb_nacionalidad.getModel();
        DefaultListModel modelolistapaises = (DefaultListModel) listapaises.getModel();
        for (int i = 0; i < agregarpaises.size(); i++) {
            modelopaises.addElement(agregarpaises.get(i));
            modelolistapaises.addElement(agregarpaises.get(i));
        }
        listapaises.setModel(modelolistapaises);
        cb_nacionalidad.setModel(modelopaises);

    }

    public void agregareventoalarchivo(Eventos e) {
        try {
            File archivo = new File("./Eventos.ev");
            FileOutputStream fw = new FileOutputStream(archivo);
            ObjectOutputStream bw = new ObjectOutputStream(fw);
            bw.writeObject(e);
            bw.flush();
            bw.close();
            fw.close();
        } catch (Exception x) {
        }

    }

    public ArrayList<Eventos> recibirarchivo() {
        ArrayList<Eventos> eventillos = new ArrayList();
        try {
            File archivo = new File("./Eventos.ev");
            FileInputStream fw = new FileInputStream(archivo);
            ObjectInputStream bw = new ObjectInputStream(fw);
            Eventos eventsoaux = new Eventos();
            while ((eventsoaux = (Eventos) bw.readObject()) != null) {
                eventillos.add(eventsoaux);
            }

        } catch (Exception e) {
        }

        return eventillos;
    }

    public void agregarnadadoralarchivo(Nadador a) {
        try {
            File archivo = new File("./Nadador.nd");
            FileOutputStream fw = new FileOutputStream(archivo);
            ObjectOutputStream bw = new ObjectOutputStream(fw);
            bw.writeObject(a);
            bw.flush();
            bw.close();
            fw.close();
        } catch (Exception x) {
        }

    }

    public ArrayList<Nadador> recibirarchivonadadores() {
        ArrayList<Nadador> nadadoresaux = new ArrayList();
        try {
            File archivo = new File("./Nadador.nd");
            FileInputStream fw = new FileInputStream(archivo);
            ObjectInputStream bw = new ObjectInputStream(fw);
            Nadador temp = new Nadador();
            while ((temp = (Nadador) bw.readObject()) != null) {
                nadadoresaux.add(temp);
            }
            bw.close();
            fw.close();
        } catch (Exception e) {
        }
        return nadadoresaux;
    }

    public void movercontadores(ArrayList<Nadador> n) {

        for (int i = 0; i < n.size(); i++) {
            if (n.get(i).getEstilonatacion().equalsIgnoreCase("libre")) {
                contlibre++;
            }
            if (n.get(i).getEstilonatacion().equalsIgnoreCase("pecho")) {
                contpecho++;
            }
            if (n.get(i).getEstilonatacion().equalsIgnoreCase("dorso")) {
                contdorso++;
            }
            if (n.get(i).getEstilonatacion().equalsIgnoreCase("mariposa")) {
                contmariposa++;
            }

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }
    ArrayList<Nadador> nadadores = new ArrayList();
    ArrayList<Pais> paises = new ArrayList();
    ArrayList<Eventos> eventos = new ArrayList();
    int contlibre = 0;
    int contpecho = 0;
    int contdorso = 0;
    int contmariposa = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_distancia;
    private javax.swing.JComboBox<String> cb_distanciaevento;
    private javax.swing.JComboBox<String> cb_estilo;
    private javax.swing.JComboBox<String> cb_estilos;
    private javax.swing.JComboBox<String> cb_nacionalidad;
    private javax.swing.JComboBox<String> cb_nadadoresagregar;
    private javax.swing.JButton crearpais;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listapaises;
    private javax.swing.JTextField nombrenadador;
    private javax.swing.JSpinner sp_edadnadador;
    private javax.swing.JSpinner sp_numeromedallas;
    private javax.swing.JSpinner sp_nummedallas;
    private javax.swing.JSpinner sp_records;
    private javax.swing.JSpinner sp_tiempomasrapido;
    private javax.swing.JTextField txt_estatura;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
